services:
  db:
    image: postgres:latest
    container_name: edutrack_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: edutrack_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # Changed from 5432:5432
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_edutrack
    restart: always
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  db_data:
  pgadmin_data: